/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SecureVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "calculateAccessPermissionsEnc"
      | "computeAccessPermissionsEnc"
      | "confidentialProtocolId"
      | "getMyIdentityData"
      | "getMyLastPermissionsEnc"
      | "hasStoredData"
      | "isAdultEncrypted"
      | "isInRegionEncrypted"
      | "isKycVerifiedEncrypted"
      | "storeIdentityData"
      | "updateIdentityData"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "calculateAccessPermissionsEnc",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "computeAccessPermissionsEnc",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyIdentityData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyLastPermissionsEnc",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasStoredData",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdultEncrypted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isInRegionEncrypted",
    values: [AddressLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isKycVerifiedEncrypted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storeIdentityData",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIdentityData",
    values: [BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateAccessPermissionsEnc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "computeAccessPermissionsEnc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyIdentityData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyLastPermissionsEnc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hasStoredData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAdultEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInRegionEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isKycVerifiedEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storeIdentityData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIdentityData",
    data: BytesLike
  ): Result;
}

export interface SecureVault extends BaseContract {
  connect(runner?: ContractRunner | null): SecureVault;
  waitForDeployment(): Promise<this>;

  interface: SecureVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  calculateAccessPermissionsEnc: TypedContractMethod<
    [allowedRegionHandle: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;

  computeAccessPermissionsEnc: TypedContractMethod<
    [user: AddressLike, allowedRegionHandle: BytesLike, proof: BytesLike],
    [[string, string] & { permissionA: string; permissionB: string }],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  getMyIdentityData: TypedContractMethod<
    [],
    [[string, string, string]],
    "view"
  >;

  getMyLastPermissionsEnc: TypedContractMethod<
    [],
    [[string, string] & { permissionA: string; permissionB: string }],
    "view"
  >;

  hasStoredData: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isAdultEncrypted: TypedContractMethod<
    [user: AddressLike],
    [string],
    "nonpayable"
  >;

  isInRegionEncrypted: TypedContractMethod<
    [user: AddressLike, regionHandle: BytesLike, proof: BytesLike],
    [string],
    "nonpayable"
  >;

  isKycVerifiedEncrypted: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  storeIdentityData: TypedContractMethod<
    [
      ageHandle: BytesLike,
      regionHandle: BytesLike,
      kycHandle: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  updateIdentityData: TypedContractMethod<
    [
      ageHandle: BytesLike,
      regionHandle: BytesLike,
      kycHandle: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "calculateAccessPermissionsEnc"
  ): TypedContractMethod<
    [allowedRegionHandle: BytesLike, proof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "computeAccessPermissionsEnc"
  ): TypedContractMethod<
    [user: AddressLike, allowedRegionHandle: BytesLike, proof: BytesLike],
    [[string, string] & { permissionA: string; permissionB: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMyIdentityData"
  ): TypedContractMethod<[], [[string, string, string]], "view">;
  getFunction(
    nameOrSignature: "getMyLastPermissionsEnc"
  ): TypedContractMethod<
    [],
    [[string, string] & { permissionA: string; permissionB: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasStoredData"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAdultEncrypted"
  ): TypedContractMethod<[user: AddressLike], [string], "nonpayable">;
  getFunction(
    nameOrSignature: "isInRegionEncrypted"
  ): TypedContractMethod<
    [user: AddressLike, regionHandle: BytesLike, proof: BytesLike],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isKycVerifiedEncrypted"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "storeIdentityData"
  ): TypedContractMethod<
    [
      ageHandle: BytesLike,
      regionHandle: BytesLike,
      kycHandle: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateIdentityData"
  ): TypedContractMethod<
    [
      ageHandle: BytesLike,
      regionHandle: BytesLike,
      kycHandle: BytesLike,
      inputProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
